name: new-version-was-release
run-name: new-version-was-release-run-name
on: [ push ]
jobs:
  job-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    - name: SSH Remote Commands To Aws And Deploy The App
      uses: appleboy/ssh-action@v0.1.2
      with:
        key: ${{secrets.AWS_VM_SSH}}
        host: ${{secrets.AWS_VM_IP}}
        username: ${{secrets.AWS_VM_USERNAME}}
        script: |
          sudo rmdir ${{ github.event.repository.name }}
          git clone $GURL

# python3 -m http.server --bind 0.0.0.0 2000
# git clone $GURL
