name: new-version-was-release
run-name: new-version-was-release-run-name
on: [ push ]
jobs:
  job-of-pushing-to-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SSH Remote Commands To Aws And Deploy The App
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.AWS_VM_IP }}
          username: ${{ secrets.AWS_VM_USERNAME }}
          key: ${{ secrets.AWS_VM_SSH_KEY }}
          port: ${{ secrets.AWS_VM_SSH_PORT }}
          script: |
            echo $GURL
# git clone $GURL
            # python3 -m http.server --bind 0.0.0.0 2000
# sudo rmdir ${{github.event.repository.name}}
# git clone $GURL